test123

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -54,11 +54,7 @@ jobs:
       - name: Release docker image
         shell: bash
         run: |
-          ls -lA
-          if [[ ! -f "docker_digest" ]]; then
-            echo "::error file=docker_digest::docker_digest does not exists."
-            exit 1
-          fi
+          [ -f docker_digest ] || echo "::error file=docker_digest::docker_digest does not exists." && exit 1
           DIGEST=$(cat docker_digest)
           echo "Getting image ${IMAGE_BASENAME}@${DIGEST}"
           docker pull ${IMAGE_BASENAME}@${DIGEST}
